# pixeltoaster makefile for mingw (new source code layout)

flags = -s -O3 -Wall -ffast-math

source := PixelToaster.cpp
headers := $(wildcard PixelToaster*.h)

%.exe : %.cpp ${headers} makefile
	g++ $< -o $@ ${flags}

all: PixelToaster

documentation : ${source} ${headers} doxygen.config
	doxygen doxygen.config
	
docs : documentation
	
clean:
	rm -rf PixelToaster documentation
